[client]
showErrorDetails = "none"
showSidebarNavigation = false

[theme]
primaryColor = "#FF9500"  
backgroundColor = "#0A0A0A"  
secondaryBackgroundColor = "#1C1C1C"  
textColor = "#FFFFFF"  
font = "monospace"  

[server]
headless = true
enableCORS = false
enableXsrfProtection = false

